import Footer from '@/componets/@Footer/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '@/componets/@Nav/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <div> 
          {children}
        </div>
        <Footer />

        </body>
    </html>
  )
}
